GET http://localhost:5000/hotels

### 
POST http://localhost:5000/hotels 
Content-Type: application/json

{
    "name":"hotel malo", 
    "type":"hotel", 
    "city":"berlin", 
    "address":"somewhere", 
    "distance":"500", 
    "title":"best hotel in city", 
    "desc":"hotel description", 
    "cheapestPrice":100,
    "userId":"63dd4136c993d4f47cc96afd"

}

###
GET http://localhost:5000/users 

###
POST http://localhost:5000/users 
Content-Type: application/json

{
    "username":"kamal3", 
    "email":"kamal3@gemail.com", 
    "password":"123", 
    "confPassword":"123", 
    "role":"ADMIN"

}
