GET http://localhost:5000/hotels

###
POST  http://localhost:5000/hotels
Content-Type: application/json

{
    "name":"hotel malo",
    "type":"hotel",
    "city":"berlin",
    "address":"somewhere",
    "distance":"500",
    "title":"best hotel in city",
    "desc":"hotel description",
    "cheapestPrice":100,
    "userUuid":"93bc4547-2585-4508-9e70-f54ad9d8c482"
}


###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name":"kamal",
    "email":"kamal@gemail.com",
    "password":"123",
    "confPassword":"123",
    "role":"ADMIN"
}
