GET http://localhost:5000/hotels

### 
POST http://localhost:5000/hotels 
Content-Type: application/json

{
    "name":"hotel malo", 
    "type":"hotel", 
    "city":"berlin", 
    "address":"somewhere", 
    "distance":"500", 
    "title":"best hotel in city", 
    "desc":"hotel description", 
    "cheapestPrice":100,
    "userId":"64087b48f06143549b06a74c"

}

###
GET http://localhost:5000/users 

###
POST http://localhost:5000/users 
Content-Type: application/json

{
    "username":"coba1", 
    "email":"coba1@gmail.com", 
    "password":"123", 
    "confPassword":"123"
}

###
GET http://localhost:5000/users/64087b48f06143549b06a74c