GET http://localhost:5000/v1/hotels

### 
POST http://localhost:5000/v1/hotels 
Content-Type: application/json

{
    "name":"hotel coba1", 
    "type":"hotel", 
    "city":"berlin", 
    "address":"somewhere", 
    "distance":"500", 
    "title":"best hotel in city", 
    "desc":"hotel description", 
    "cheapestPrice":100,
    "userId":"a83b0223-a70b-46dd-8580-24b5406e1a90"

}

###
GET http://localhost:5000/v1/hotels/4

###
GET http://localhost:5000/v1/users 

###
POST http://localhost:5000/v1/users 
Content-Type: application/json

{
    "username":"coba2", 
    "email":"coba2@gmail.com", 
    "password":"123", 
    "confPassword":"123"
}

###
GET http://localhost:5000/v1/users/a83b0223-a70b-46dd-8580-24b5406e1a90


###
DELETE http://localhost:5000/v1/users/a83b0223-a70b-46dd-8580-24b5406e1a90